let x = 10
func main(){
  log("chao")
}
let 18numero = 24 // esto deberia dar error recuperable es decir que no se detenga la ejecucion del programa

let 243caca = 32
// esto suma
while x == 10 {
  suma()
  resta()
}

for x in 0..10 {
  vivamario()
}
